### ISSUE TITLE
Ajout de la prise en charge de la découverte côté serveur

### ISSUE THREAD

**Issue by ubervison** [RobotPiProject/RobotPiHEIG#73]
On peut configurer avahi, déjà présent sur la Raspberry Pi, pour broadcaster la présence du service `robopi-server` sur le port 2025. Avahi est une implémentation du protocole Zeroconf, aussi implémenté par Bonjour (Apple).

Le robot sera donc visible pour tous les clients sur le même réseau, qui supportent le multi-cast DNS (mDNS).

Voir la page du wiki Archlinux : [https://wiki.archlinux.org/title/Avahi](https://wiki.archlinux.org/title/Avahi)

Côté client, la librairie `jmdns` semble active et maintenue : [https://github.com/jmdns/jmdns](https://github.com/jmdns/jmdns) (doc [ici](https://www.javadoc.io/doc/org.jmdns/jmdns/latest/index.html))

Le format pour un service type est `_protocolname._tcp|_udp`. Dans notre cas, le service type sera `_robopi._tcp` : le protocol `robopi`, utilisant le protocole de transport `tcp`, et qui écoute sur le port donné. Askip [il faut s'inscrire auprès de l'IANA](http://www.dns-sd.org/ServiceTypes.html) mais balek.

**Comment by jadegrli** [comment]
pour le nom du service mettre plutôt "_robopi._tcp.local." pour chercher dans le réseau local

**Comment by ubervison** [comment]
Avec mDNS on cherche de toute façon dans le réseau local, et le daemon avahi n'aime pas qu'on définisse `_robopi._tcp.local` comme dns-sd service type. On peut laisser dans le Client, ça fonctionne, mais le serveur continuera de publier sur son réseau local.
